// @flow

export const AuthenticationActions = {
  LOGIN_BY_PHONE: 'LOGIN_BY_PHONE',
  CAN_LOGIN_BY_PASSWORD: 'CAN_LOGIN_BY_PASSWORD',
  LOGIN_BY_PASSWORD: 'LOGIN_BY_PASSWORD',
  FORGOT_PASSWORD: 'FORGOT_PASSWORD',
  VERIFY_LOGIN_CODE: 'VERIFY_LOGIN_CODE',
  VERIFY_LOGIN_CODE_FOR_CHANGE_PASSWORD: 'VERIFY_LOGIN_CODE_FOR_CHANGE_PASSWORD',
  REGISTER: 'REGISTER',
  CHANGE_PASSWORD: 'CHANGE_PASSWORD',
  LOGIN_AUTO: 'LOGIN_AUTO',
  CHOOSE_ANOTHER_PHONE_NUMBER: 'CHOOSE_ANOTHER_PHONE_NUMBER',
  LOGOUT: 'LOGOUT'
}

export const ApplicationActions = {
  TURN_ON_LOADING: 'TURN_ON_LOADING',
  TURN_OFF_LOADING: 'TURN_OFF_LOADING',
  CHANGE_LANGUAGE: 'CHANGE_LANGUAGE'
}